version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-and-patch-dependencies:
        update-types:
          - "minor"
          - "patch"
